<<<<<<< HEAD





tuto_test_first:
    path:     /test/
    defaults: { _controller: TutoTestBundle:Default:test }



tuto_test_afficher:
    path:     /index/
    defaults: { _controller: TutoTestBundle:Default:index }


tuto_test_second:
    path:     /second/
    defaults: { _controller: TutoTestBundle:Default:second }


tuto_test_third:
    path:     /third/
    defaults: { _controller: TutoTestBundle:Default:third }
=======
tuto_test_homepage:
    path:     /hello/{name}
    defaults: { _controller: TutoTestBundle:Default:index }

tuto_test_premier:
    path:     /afficher/
    defaults: { _controller: TutoTestBundle:Default:liste }


>>>>>>> upstream/dev
