parameters:
#    tuto_test.example.class: Tuto\TestBundle\Example

services:
#    tuto_test.example:
#        class: %tuto_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
