<?php

namespace Tuto\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * directorfilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class directorfilmRepository extends EntityRepository
{
}
