<?php

namespace Tuto\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FilmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmsRepository extends EntityRepository
{
}
