<?php

namespace Tuto\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * writersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class writersRepository extends EntityRepository
{
}
